### ISSUE TITLE
Make patches address independant

### ISSUE THREAD

**Issue by ghost2238** [ghost2238/sfall-asm#3]
To further support https://github.com/rotators/Fo1in2/issues/41, make it possible to write patches that are not hardcoded to specific memory addresses.

For operations such as <code>E8</code> (CALL) or <code>E9</code> (JMP) which use rel16/32 addresses we need to mark these with some meta syntax containing the absolute address within the module so that we can while generating the patch calculate the relative offset from some current address (based on what's being set as the base address).

The alternative is to use far CALL/JMP, either <code>FF /4</code> or <code>FF /5</code> in the patches instead. Since this uses the reg/op field byte, I think this not a great solution if there's a lot of jumps in the code.

Right now, the memory address 0 denotes an incremented address that continues from a previously specific address. Maybe we can use <code>[**\<identifier\>**]</code> for both memory variables and absolute addresses.

The memory variables would then be resolved by using some CLI arguments, perhaps <code>--memory-args="patch_code=0x41AE86;"</code>

It might also be a good idea to implement some patchset files where you set one memory address, e.g.  <code>main_selfrun</code> as proposed in https://github.com/rotators/Fo1in2/issues/41#issuecomment-587811478, specify which patches you want, then the correct sfall script code is generated with aligned memory addresses that don't collide. This allows doing length checks to avoid using more code memory than available.

Using [dialog_money_fix.asm](https://github.com/ghost2238/sfall-asm/blob/master/patches/dialog_money_fix.asm) as a basis for this example since it's short:

<pre>
00447ACD     | E9 [patch_code] | jmp [patch_code]
[patch_code] | 60              | pushad
00000000     | E8 [0x446D30]   | call fallout2.gdProcessUpdate_
00000000     | 61              | popad
00000000     | E8 [0x4D6DAC]   | call fallout2.win_show_
00000000     | E9 [0x447AD2]   | jmp fallout2.447AD2
</pre>

# References
http://ref.x86asm.net/coder32.html#xE8 - E8/E9 encoding
https://www.felixcloutier.com/x86/jmp - Different jumps

**Comment by ghost2238** [comment]
Implemented, but with a small adjustment, <code>--memory-args</code> use ' instead of " to avoid escaping.

**Comment by wipe2238** [comment]
Why `'` is even needed in a first place? It makes using app from bash awkward :(
`$ ./sfall-asm.exe patches/dialog_money_fix.asm --memory-args=\'patch=0x1207\'`
Can it be something like `--memory-args=name1=0x1207,name2=0x1337`?

Other thing - `bytes` string have no longer guaranteed % 2 == 0 length, which breaks conversion for scripts :(
`$ ./sfall-asm.exe patches/dialog_money_fix.asm --memory-args=\'patch=0x480E1F\'`

**Comment by ghost2238** [comment]
It's not needed unless support for spaces is needed, which isn't needed, at the moment. It was more of a convention thing I guess. I'll remove it.

Thanks for once again catching me doing too little testing and error checking, I'll fix the byte string length by padding with zeroes, should fix the issue :)
