### ISSUE TITLE
Asm utility code

### ISSUE THREAD

**Issue by ghost2238** [ghost2238/sfall-asm#5]
If we want to stay sane while being sfall vanilla compatible, we need a few utility functions that can also be depended on in patches, meaning they can be called with a <code>E8 [util::VirtualProtect]</code> (after pushing appropriate args)

I have two functions in mind right now which are connected:
## GetSfallFuncAddress - Get address to sfall::SomeFunc+0x1207
Something similar to:
<pre>
0041AE06 | 2EA1 70464C00    | mov eax,cs:[4C4670]
/// Calculate where ddraw.sfall::wmAreaMarkVisitedState_hack+0x51 is
0041AE0C | BA C5464C00      | mov edx,fallout2.4C46C5
0041AE11 | 01D0             | add eax,edx
0041AE13 | 89C6             | mov esi,eax
</pre>

Would be used like this:
<pre>
push [jmp/call offset + 1] 
004C466F | E9 AC451702 
              ^------ this is the address that we need to push, the one after a jmp/call instruction
push [offset in the sfall handler func that we are interested in, for instance 0x51]
call [utility.GetSfallFuncAddress]
// Now the result is in eax, as expected
</pre>
## VirtualProtect
We can find the address of Kernel32's VirtualProtect by using the location of a known HRP hook in Fallout2.exe, since we know all the addresses relative to some hook that we can assume will always be there, we can easily find VirtualProtect and call it with pushed args. 

This is needed for patches modifying sfall code.

## Meta code
While we are doing all this in a code generation mode, why not just drop the need to write manual asm and allow the use of some meta function convention like <util::GetSfallFuncAddress(0x4C4670, 0x51)> in the patches.

Which generates the following code:
<pre>
push 0x4C4670
push 0x51
call [rel_address to util::GetSfallFuncAddress]
</pre>

Not a huge difference in this case, but might be useful for other things.

More useful is util::SetSfallCode(0x4C4670, 0x51, 0x0) - which will generate code bytes with the same functionality as [no_location_radius.asm](../tree/master/patches/no_location_radius.asm)

## In the end, it doesn't even...
Yay, nay, meh?

**Comment by wipe2238** [comment]
> VirtualProtect

How about `0x4fdfa4` / `0x6c0218`, can it be used?

![obraz](https://user-images.githubusercontent.com/1433300/74930937-e7801f00-53de-11ea-8759-20fac9c407ba.png)

If yes, there's quite few kernel32/user32 jumps out there which _might_ or _might not_ be interesting. There's even some ddraw stuff, but dunno how useful it can be.

**Comment by ghost2238** [comment]
Looks like <code>0x6c0218</code> can indeed be used!

**Comment by wipe2238** [comment]
I'd really love to use `SafeMemSet()`; sfall answer is exactly like i though it will be.

**Comment by ghost2238** [comment]
The VirtualProtect issue was solved and I've added a working [SafeMemSet8](../blob/master/lib/memset.asm) as a library patch.

Was also added to fo1in2 in https://github.com/rotators/Fo1in2/commit/63544ef7f0e1146468482f5ae38b835c03ea36a5 as a replacement for the old VOODOO_CAVE code.

<code>GetSfallFuncAddress</code> and/or <code>SafeWriteSfall</code> might be worth adding if there's more than one patch using it. In such a case, a new issue can be opened since there's not much point in doing further work if it's not going to used by anyone.
