### ISSUE TITLE
Switch to using `$` in global variables

### ISSUE THREAD

**Issue by wipe2238** [ghost2238/sfall-asm#9]
Apparently `$` can be used in variables names and `variable $name` is perfectly fine in CAH. Which is great actually, as none of scripts uses such naming (and probably never will) so we can be sure variables we add to scripts global scope won't conflict with regular variables (even if we use very generic names).

TODO **after** FO1@2 v1.1 release
```
06:38 < lexx> great, tp to mariposa crashes the game
06:38 < lexx> tp to anywhere crashes the game
06:39 < lexx> i bet it#s related to you peoples voodoo stuff again
06:40 < lexx> ok updating latest scripts fixed it.. your luck
```
(Spoiler: i have no idea what could cause it so i'm happy it autofixed itself 😅)

**Comment by ghost2238** [comment]
Sounds like a good principle. I'll see if I can improve the global variable handling/generation in sfall-asm a bit too.
